### ISSUE TITLE
How to connect to WSS

### ISSUE THREAD

**Issue by ycherniavskyi** [jeffgrunewald/glock#10]
Could you please suggest how to connect to `wss://echo.websocket.org` (current example show how to connect to `ws://echo.websocket.org`)?
Is it possible at all?

I tried
```elixir
MySocket.start_link(host: "echo.websocket.org", path: "/", port: 443)
```
and also
```elixir
MySocket.start_link(connect_opts: %{transport: :tls}, host: "echo.websocket.org", path: "/", port: 443)
```
and nothing seems to works ☹️.

**Comment by ycherniavskyi** [comment]
As I understand the issue is related to supported versions of TLS by `echo.websocket.org` server, so some additional configuration of erlang `ssl` is necessary.

**Comment by jeffgrunewald** [comment]
I'm afraid Gun is not very well documented for SSL/TLS connection options required; are you aware of the configuration changes necessary to connect to this version of TLS?

**Comment by dcrck** [comment]
From the [Gun WebSocket docs](https://ninenines.eu/docs/en/gun/1.3/guide/websocket/):

> Only HTTP/1.1 connections can be upgraded to Websocket, so **you might need to restrict the protocol to HTTP/1.1 if you are planning to use Websocket over TLS.**

From the [connection option documentation](https://ninenines.eu/docs/en/gun/1.3/manual/gun/#_opts)
> **Protocols**
>  Ordered list of preferred protocols. When the transport is `tcp`, this list must contain exactly one protocol. When the transport is `tls`, this list must contain at least one protocol and will be used to negotiate a protocol via ALPN. When the server does not support ALPN then `http` will always be used. **Defaults to `[http]` when the transport is `tcp`, and `[http2, http]` when the transport is `tls`.**

You're using the TLS transport, which means you need to manually restrict the protocol list to just `[:http]`. This should work:

```
MySocket.start_link(connect_opts: %{transport: :tls, protocols: [:http]}, host: "echo.websocket.org", path: "/", port: 443)
```

**Comment by ycherniavskyi** [comment]
@dcrck thank you for your comment.

For now, I decided to use Gun directly, and got next call:
```
{:ok, client} = :gun.open('echo.websocket.org', 443, %{transport: :tls, protocols: [:http], transport_opts: [verify: :verify_none, log_level: :debug]})
```

But as result, I can't connect to `echo.websocket.org` server, because it uses TLS 1.1 with some odd security config and elixir, as I understand, uses TLS 1.2, and for TLS 1.1 some additional configuration requare. To servers with TLS 1.2 it connects without any issue 😊.
